# Generated by Django 3.0.6 on 2020-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_sh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='Problem_Setter',
            field=models.CharField(max_length=50),
        ),
    ]
