# Generated by Django 3.0.6 on 2020-06-02 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Code_sh', '0002_auto_20200531_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('Problem', models.CharField(max_length=50, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Number', models.IntegerField(default=0)),
            ],
        ),
    ]
