# Generated by Django 3.0.6 on 2020-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_sh', '0004_auto_20200602_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solved',
            name='Problem',
            field=models.CharField(max_length=50),
        ),
    ]
